# Generated by Django 5.0.7 on 2024-09-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gpxtrack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpxtrack',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='gpxtrack',
            old_name='gpx_file',
            new_name='file',
        ),
    ]
