# Generated by Django 5.0.7 on 2024-09-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_uploaded_at_gpxtrack_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpxtrack',
            name='created_at',
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='elevation_gain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='length_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
