# Generated by Django 5.0.7 on 2024-09-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_gpxtrack_created_at_gpxtrack_elevation_gain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpxtrack',
            name='elevation_gain',
        ),
        migrations.RemoveField(
            model_name='gpxtrack',
            name='length_km',
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpxtrack',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
