# Generated by Django 5.0.7 on 2024-09-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_gpxtrack_elevation_gain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtrack',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='elevation_gain',
            field=models.FloatField(default=0),
        ),
    ]
