# Generated by Django 5.0.7 on 2024-09-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_gpxtrack_distance_gpxtrack_elevation_gain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='track_photos/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.gpxtrack')),
            ],
        ),
    ]
