# Generated by Django 5.0.7 on 2024-09-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpxtrack',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='gpxtrack',
            name='elevation_gain',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
