# Generated by Django 5.0.7 on 2024-09-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
    ]
